Adding legal notice page
vasilvestre/vasilvestre.github.io pull request #144
Opened 2023-04-12 21:25 UTC by Zveltana

Close #143

2023-04-13 08:25 UTC, vasilvestre requested changes

2023-04-13 08:25 UTC, vasilvestre commented on .github/workflows/build.yaml
> +name: Build
J'ai déjà un fichier de build, pas besoin de celui la

2023-04-13 08:25 UTC, vasilvestre commented on assets/front/images/portrait-valentin.png
J'ai déjà cette photo dans le repo je crois, peut-être en jpg. Je crois que l'html n'utilise pas les png

2023-04-13 08:25 UTC, vasilvestre commented on assets/front/images/valentin-contact.png
J'ai déjà cette photo dans le repo je crois, peut-être en jpg. Je crois que l'html n'utilise pas les png

2023-04-13 08:25 UTC, vasilvestre commented on package-lock.json
Tu as pas modifié les dépendances, pourquoi le lock.json a changé ?

2023-04-13 08:25 UTC, vasilvestre commented on public/CNAME
Pas besoin de CNAME sur le repo, en + la valeur est incorrecte

2023-04-13 08:25 UTC, vasilvestre commented on public/index.html
Ok pour déplacer les tags mais tu as changé les valeurs que j'avais mises qui sont custom

2023-04-14 07:17 UTC, vasilvestre requested changes

2023-04-14 07:17 UTC, vasilvestre commented on public/index.html
> +            <div class="mt-8 md:mt-0">
J'aimerais bien garder cette info centrée stp :)

2023-04-14 09:05 UTC, vasilvestre requested changes

2023-04-14 09:05 UTC, vasilvestre commented on public/index.html
> -    <script defer data-domain="vasilvestre.github.io" src="https://analytics.nicolasmylle.fr/js/script.js"></script>
Tu peux remettre le lien de l'analytics stp ? :D

2023-04-14 09:05 UTC, vasilvestre commented on public/index.html
> +                            <p class="mt-6 text-xl text-light-green">A simple and flexible plugin built on top of Sylius ecommerce platform. Same spirit, same possibilities.</p>
Le texte à sauté ici

2023-04-14 09:05 UTC, vasilvestre commented on public/index.html
> +                            <a href="#contact" class="text-center block w-2/4 rounded-br-2xl rounded-tl-2xl border border-transparent px-5 py-3 bg-beige text-base font-medium text-green-tree shadow h
Tu as fait exprès de changer le style?

2023-04-14 09:05 UTC, vasilvestre commented on public/index.html
> +                    <img src="build/front/images/portrait-valentin.jpg" alt="photo de valentin silvestre" class="mx-auto rounded-full border-4 border-b-8 border-light-green w-72 h-full lg:w-96">
Tu as fait exprès de changer le style?

2023-04-14 09:05 UTC, vasilvestre commented on public/index.html
> +                    <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At blanditiis dolor doloremque earum
Le texte à sauter ici

2023-04-14 09:05 UTC, vasilvestre commented on public/index.html
> +                                            Create an unlimited number of sellers. Add a seller to products,
Le texte à sauter ici

2023-04-14 09:05 UTC, vasilvestre commented on public/index.html
> +                                        <h2 class="mt-6 text-lg font-medium tracking-tight text-dark-blue">PHP</h2>
Le H3 est devenu un h2, c'est fait exprès ?

2023-04-14 09:05 UTC, vasilvestre commented on public/index.html
> +                                            Sellers can view their customers and are able to create customer groups including a default one.
Le texte à sauter ici

2023-04-14 09:05 UTC, vasilvestre commented on public/index.html
> +                                        <h2 class="mt-6 text-lg font-medium tracking-tight text-dark-blue">Symfony</h2>
h2 ?

2023-04-14 09:16 UTC, Zveltana commented on public/index.html
> +                                        <h2 class="mt-6 text-lg font-medium tracking-tight text-dark-blue">PHP</h2>
yep parce qu'on ne peut pas passer du h1 au h3 directement, donc j'ai remplacé en h2

2023-04-14 09:43 UTC, vasilvestre approved these changes

2023-04-14 09:44 UTC, merged